[project]
name = "weather-app"
version = "0.1.0"
description = "WeatherApp is an application designed to display current weather information for selected cities."
readme = "README.md"
requires-python = ">=3.12"
authors = [
    {name = "Elias-Wide", email = "ilshi2904@gmail.com"}
]
dependencies = [
  "flet==0.27.6",
  "mtranslate>=1.8",
  "pydantic_settings==2.9.1",
  "sqlalchemy>=2.0.40",
  "cachetools>=5.5.2",
  "requests>=2.32.3",
  "toml>=0.10.2"
]

[tool.flet]
org = "com.mycompany"
# project display name that is used as an app title on Android and iOS home screens,
# shown in window titles and about app dialogs on desktop.
product = "weather-app"

# company name to display in about app dialogs
company = "Flet"

# copyright text to display in about app dialogs
copyright = "Copyright (C) 2025 by Flet"

[tool.flet.app]
module = "main"
path = "src"
include = [ "main.env", "weather_api.txt"]


[tool.uv]
dev-dependencies = [
    "flet[all]==0.27.6",
]

[tool.poetry]
package-mode = true

[tool.poetry.group.dev.dependencies]
flet = {extras = ["all"], version = "0.27.6"}
